name = "discord-openrouter-bot"
main = "src/index.js"
compatibility_date = "2023-10-30"

[vars]
CHANNEL_ID = "1344773348932063324"

# Secrets that will be encrypted
# Run these commands to set them up:
# npx wrangler secret put BOT_TOKEN
# npx wrangler secret put OPENROUTER_API_KEY